/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as BookingTermsRouteImport } from './routes/booking-terms'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GuestGuidelinesRouteImport } from './routes/guest-guidelines'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ListYourPropertyRouteImport } from './routes/list-your-property'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as DestinationsSlugRouteImport } from './routes/destinations_.$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences_.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal_.$slug'
import { Route as PropertiesSlugRouteImport } from './routes/properties_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTermsRoute = BookingTermsRouteImport.update({
  id: '/booking-terms',
  path: '/booking-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestGuidelinesRoute = GuestGuidelinesRouteImport.update({
  id: '/guest-guidelines',
  path: '/guest-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourPropertyRoute = ListYourPropertyRouteImport.update({
  id: '/list-your-property',
  path: '/list-your-property',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations_/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences_/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal_/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties_/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-terms': typeof BookingTermsRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guest-guidelines': typeof GuestGuidelinesRoute
  '/journal': typeof JournalRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-terms': typeof BookingTermsRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guest-guidelines': typeof GuestGuidelinesRoute
  '/journal': typeof JournalRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-terms': typeof BookingTermsRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guest-guidelines': typeof GuestGuidelinesRoute
  '/journal': typeof JournalRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRoute
  '/destinations_/$slug': typeof DestinationsSlugRoute
  '/experiences_/$slug': typeof ExperiencesSlugRoute
  '/journal_/$slug': typeof JournalSlugRoute
  '/properties_/$slug': typeof PropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/booking-terms'
    | '/cancellation-policy'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faq'
    | '/favorites'
    | '/guest-guidelines'
    | '/journal'
    | '/list-your-property'
    | '/privacy-policy'
    | '/properties'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/journal/$slug'
    | '/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/booking-terms'
    | '/cancellation-policy'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faq'
    | '/favorites'
    | '/guest-guidelines'
    | '/journal'
    | '/list-your-property'
    | '/privacy-policy'
    | '/properties'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/journal/$slug'
    | '/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/booking-confirmation'
    | '/booking-terms'
    | '/cancellation-policy'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faq'
    | '/favorites'
    | '/guest-guidelines'
    | '/journal'
    | '/list-your-property'
    | '/privacy-policy'
    | '/properties'
    | '/destinations_/$slug'
    | '/experiences_/$slug'
    | '/journal_/$slug'
    | '/properties_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BookingTermsRoute: typeof BookingTermsRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  GuestGuidelinesRoute: typeof GuestGuidelinesRoute
  JournalRoute: typeof JournalRoute
  ListYourPropertyRoute: typeof ListYourPropertyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertiesRoute: typeof PropertiesRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-terms': {
      id: '/booking-terms'
      path: '/booking-terms'
      fullPath: '/booking-terms'
      preLoaderRoute: typeof BookingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-guidelines': {
      id: '/guest-guidelines'
      path: '/guest-guidelines'
      fullPath: '/guest-guidelines'
      preLoaderRoute: typeof GuestGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-property': {
      id: '/list-your-property'
      path: '/list-your-property'
      fullPath: '/list-your-property'
      preLoaderRoute: typeof ListYourPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations_/$slug': {
      id: '/destinations_/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/$slug': {
      id: '/experiences_/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal_/$slug': {
      id: '/journal_/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/$slug': {
      id: '/properties_/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  BookingTermsRoute: BookingTermsRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  GuestGuidelinesRoute: GuestGuidelinesRoute,
  JournalRoute: JournalRoute,
  ListYourPropertyRoute: ListYourPropertyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertiesRoute: PropertiesRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
